#!/bin/sh
/sbin/iptables -A INPUT -p udp --dport 5353 -j DROP
/sbin/iptables -A OUTPUT -p udp --dport 5353 -j DROP
/sbin/iptables -A INPUT -p udp --sport 5353 -j DROP
/sbin/iptables -A OUTPUT -p udp --sport 5353 -j DROP
/sbin/ip6tables -A INPUT -p udp --dport 5353 -j DROP
/sbin/ip6tables -A OUTPUT -p udp --dport 5353 -j DROP
/sbin/ip6tables -A INPUT -p udp --sport 5353 -j DROP
/sbin/ip6tables -A OUTPUT -p udp --sport 5353 -j DROP
